config/routes.rb
Out::Application.routes.draw do
  devise_for :users
  get "stocks/index"
  get "locations/test"
  resources :locations

   root 'locations#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
	#attr_accessible :address, :latitude, :longitude
	geocoded_by :address
	after_validation :geocode
end

app/models/stock.rb
class Stock < ActiveRecord::Base
	
	#named_scope :filter, lambda { |low, high| { :conditions => { :price => low..high } } }
	
	def self.high_low_prices
    	[Stock.minimum(:price), Stock.maximum(:price)]
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

# def location
#   if params[:location].blank?
#     if Rails.env.test? || Rails.env.development?
#       @location ||= Geocoder.search("50.78.167.161").first
#     else
#       @location ||= request.location#provided by gem
#     end
#   else
#     params[:location].each {|l| l = l.to_i } if params[:location].is_a? Array
#     @location ||= Geocoder.search(params[:location]).first
#     @location
#   end
# end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @locations = Location.all
    # @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
    #   marker.lat location.latitude
    #   marker.lng location.longitude
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location found!' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude, :amount)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

	def index
		unless params[:low] && params[:high]
      		@stocks = Stock.all
    	else
      		@stocks = Stock.filter(params[:low], params[:high])
    	end
    	@price_range = Stock.high_low_prices
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Out</title>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

<%= stylesheet_link_tag 'jquery-ui.css' %>

<%= javascript_include_tag 'jquery-ui.js', 'jquery-ui.min.js' %>
  </head>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Your Settings', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<script>
var map;

function initialize() {
  var mapOptions = {
    zoom: 6
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  // Try HTML5 geolocation
  if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = new google.maps.LatLng(position.coords.latitude,
                                       position.coords.longitude);
       // what shows up in the little information box above your location
      var infowindow = new google.maps.InfoWindow({
        map: map,
        position: pos,
        content: 'FOUND YOU!'
      });

      map.setCenter(pos);
    }, function() {
      handleNoGeolocation(true);
    });
  } else {
    // If Browser doesn't support Geolocation
    alert("Sorry son, your browser is too ancient.")
  }
}

//initializes  the whole map
google.maps.event.addDomListener(window, 'load', initialize);
</script> 
<script>
$(function() {
$( "#slider" ).slider({
value:100,
min: 0,
max: 50,
step: 10,
slide: function( event, ui ) {
$( "#location_amount" ).val( ui.value );
}
});
$( "#location_amount" ).val( $( "#slider" ).slider( "value" ) );
});
</script>


  <%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <title>Geolocation</title>  
.
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>

 <div id="map-canvas"></div>
  <p><h3>Enter your location:</h3></p>

  <p><%= f.text_field :address %></p>

  <p><%= f.hidden_field :latitude %></p>

  <p><%= f.hidden_field :longitude %></p>

  <p><div id="slider"></div></p>

  <p><%= f.text_field :amount %></p>

  <p><%= f.submit "Start searching" %></p>
  <% end %>
</body>
</html>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p><h1>Out?</h1></p>

<p id="demo">Click the button to get your coordinates:</p>

<button onclick="getLocation()">Try It</button>

<script>
var x = document.getElementById("demo");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
    x.innerHTML="Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude;	
}
</script>

<p><h3>How much have you got?</h3></p>
<script>
$(function() {
$( "#slider" ).slider({
value:100,
min: 0,
max: 500,
step: 10,
slide: function( event, ui ) {
$( "#amount" ).val( "£" + ui.value );
}
});
$( "#amount" ).val( "£" + $( "#slider" ).slider( "value" ) );
});
</script>
</head>
<body>
<p>
<label for="amount">Your pocket:</label>
<input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
</p>
<div id="slider"></div>
<%= link_to "Go", :controller => "locations", :action => "new" %>
</body>
</html>

 

app/views/locations/new.html.erb
<h1>Out logo here</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<p>
  <strong>Your location:</strong>
  <%= @location.address %>
</p>


    <% @locations.each do |location| %>

      <tr>
        <td><%= location.address %></td><br>
        <td><%= location.longitude %></td><br>
        <td><%= location.latitude %></td>
      </tr>
    <% end %>


<h3>Nearby activities</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.latitude, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/locations/test.html.erb
<!doctype html>
<html>
  <head>
  	<meta charset="utf-8">
  	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  	<!--<script type="text/javascript" src="http://www.parsecdn.com/js/parse-1.2.16.min.js"></script> -->
  	<script type="text/javascript" src="javascripts/custom.js"></script>
  	<link rel="stylesheet" type="text/css" href="../stylesheets/main.css">
    <script src="../../assets/javascripts/custom.js"></script>
    <link href="../dist/stylesheets/main.css" rel="stylesheet">

    <title>Out</title>
  </head>
  <body>
  <!-- first -->

  <div id="firstScreen">
  	<div id="firstLogo">
  		<img src="images/logo.png" class="logo">
  	</div>
  	<div id="moneySlider">
  		<div id="slider">
			<input class="bar" type="range" id="rangeinput" value="50" onchange="rangevalue.value=value"/>
			<span class="highlight"></span>
			<output id="rangevalue">50</output>
		</div>
  	</div>
    
  	<button id="submitButton">Go</button>
  	
  </div>

  <!-- second -->
  <div id="secondScreen">
  	<div id="topHeader">
    	<div id="logo_small">
    		<img src="resources/img/logo_small.png">
    	</div>
    	<div id="login"></div>
    </div>
    <div></div>
    <div></div>
    <div></div>
  </div>
    
  </body>
</html>

app/views/stocks/_stock_list.html.erb
<% @stocks.each do |stock| %>
  <li>
      <p><%= stock.name %></p>
      <p><%= stock.price %></p>
  </li>
<% end  %>

app/views/stocks/index.html.erb
<script type="text/javascript">
      $(function() {
        $("#x_slider").slider( { 
          range: true,
          step: 10,
          max: <%= @price_range.last %>,
          min: <%= @price_range.first %>,
          values: [<%= @price_range.first %>, <%= @price_range.last %> ],
          stop: function(event, ui) {
            var prices = $('#x_slider').slider('option', 'values');
            $('#x_low_selected').html(prices[0]);
            $('#x_high_selected').html(prices[1]);
            $.ajax({
              type: "GET",
              data: ({ low: prices[0], high: prices[1] }),
              url: 'http://0.0.0.0:3000/stocks',
              dataType: 'script'
            });
          }
        });
      });
    </script>
<div id="x_slider" style="font-size:62.5%; width:350px;"></div>

<div>
       <p>Showing all stocks between <span id="x_low_selected"><%= @price_range.first %></span> and <span id="x_high_selected"><%= @price_range.last %></span></p>
</div>

 <ul id="x_stock_list">
   <%= render 'stock_list', :stocks => @stocks %>
 </ul>